:fields:
:messages:
  :start: "ğŸŒŠ GotSurf Bot.\nCheck https://github.com/eddygarcas/gotsurfbot for updates\nSelect one surf spot available..."
  :error: "ğŸ¤– Oops! Something went wrong, please press /start button again."
  :help: "â„¹ï¸ Use inline buttons below here or type the inline command @GotSurfBot in any chat, the bot will prompt all surf spots available."
  :inline: "ğŸ”˜ Select one surf spot available"
  :link: "ğŸ§‘â€ğŸ’» Author @eddygarcas Github https://github.com/eddygarcas/gotsurfbot ğŸ¨ Bot Icon made by http://www.freepik.com"
  :credit:
:bot:
  :list: "ğŸ¤– Hey! check out spots available..."